package uk.co.pdintel.payment.domain;

/**
 * JPA entity representing a processed Stripe webhook event.
 *
 * <p>Decisions:
 * <ul>
 *   <li>stripeEventId as @Id — Stripe event IDs (evt_xxx) are globally unique.
 *       Using it directly as PK gives the unique constraint and index in one shot,
 *       no surrogate UUID needed.</li>
 *   <li>No @GeneratedValue — PK is set by the application from Stripe's event ID,
 *       not generated by the DB.</li>
 *   <li>Insert-only — no updated_at column. Written once when the event is first
 *       processed; never updated. An updated_at column would be meaningless.</li>
 *   <li>No FK to users or subscriptions — must be writable before any subscription
 *       row exists (race condition protection). This table is a pure idempotency guard.</li>
 *   <li>Written atomically with stripe_event_outbox in the same transaction —
 *       if either write fails, both are rolled back.</li>
 *   <li>@CreationTimestamp on processedAt — Hibernate sets it automatically on insert.</li>
 * </ul>
 *
 * @author Pawan
 * @copyright 2026
 */

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;

import java.time.OffsetDateTime;

@Entity
@Table(name = "processed_stripe_events")
public class ProcessedStripeEvent {

    @Id
    @Column(name = "stripe_event_id", nullable = false, updatable = false)
    private String stripeEventId;

    @Column(name = "event_type", nullable = false, updatable = false)
    private String eventType;

    @CreationTimestamp
    @Column(name = "processed_at", updatable = false, nullable = false)
    private OffsetDateTime processedAt;

    protected ProcessedStripeEvent() {
    }

    public ProcessedStripeEvent(String stripeEventId, String eventType) {
        this.stripeEventId = stripeEventId;
        this.eventType = eventType;
    }

    public String getStripeEventId() { return stripeEventId; }

    public String getEventType() { return eventType; }

    public OffsetDateTime getProcessedAt() { return processedAt; }
}
